// <auto-generated />
using System;
using Glosolalia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Glosolalia.Data.Migrations
{
    [DbContext(typeof(GlosolaliaContext))]
    [Migration("20230502194920_Database Glosolalia 0.1")]
    partial class DatabaseGlosolalia01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnWordPlWord", b =>
                {
                    b.Property<int>("EnWordsId")
                        .HasColumnType("int");

                    b.Property<int>("PlWordsId")
                        .HasColumnType("int");

                    b.HasKey("EnWordsId", "PlWordsId");

                    b.HasIndex("PlWordsId");

                    b.ToTable("EnWordPlWord");
                });

            modelBuilder.Entity("Glosolalia.Business.Entities.EnWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastInput")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PartOfSpeechId")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LastInput");

                    b.HasIndex("PartOfSpeechId");

                    b.HasIndex("Progress");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("EnWords");
                });

            modelBuilder.Entity("Glosolalia.Business.Entities.PartOfSpeech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PartsOfSpeech");
                });

            modelBuilder.Entity("Glosolalia.Business.Entities.PlWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastInput")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PartOfSpeechId")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LastInput");

                    b.HasIndex("PartOfSpeechId");

                    b.HasIndex("Progress");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("PlWords");
                });

            modelBuilder.Entity("Glosolalia.Business.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EnWordId")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int?>("PlWordId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EnWordId");

                    b.HasIndex("PlWordId");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("EnWordPlWord", b =>
                {
                    b.HasOne("Glosolalia.Business.Entities.EnWord", null)
                        .WithMany()
                        .HasForeignKey("EnWordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glosolalia.Business.Entities.PlWord", null)
                        .WithMany()
                        .HasForeignKey("PlWordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Glosolalia.Business.Entities.EnWord", b =>
                {
                    b.HasOne("Glosolalia.Business.Entities.PartOfSpeech", "PartOfSpeech")
                        .WithMany()
                        .HasForeignKey("PartOfSpeechId");

                    b.Navigation("PartOfSpeech");
                });

            modelBuilder.Entity("Glosolalia.Business.Entities.PlWord", b =>
                {
                    b.HasOne("Glosolalia.Business.Entities.PartOfSpeech", "PartOfSpeech")
                        .WithMany()
                        .HasForeignKey("PartOfSpeechId");

                    b.Navigation("PartOfSpeech");
                });

            modelBuilder.Entity("Glosolalia.Business.Entities.Tag", b =>
                {
                    b.HasOne("Glosolalia.Business.Entities.EnWord", null)
                        .WithMany("Tags")
                        .HasForeignKey("EnWordId");

                    b.HasOne("Glosolalia.Business.Entities.PlWord", null)
                        .WithMany("Tags")
                        .HasForeignKey("PlWordId");
                });

            modelBuilder.Entity("Glosolalia.Business.Entities.EnWord", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Glosolalia.Business.Entities.PlWord", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
