// <auto-generated />
using System;
using Glosolalia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Glosolalia.Data.Migrations
{
    [DbContext(typeof(GlosolaliaContext))]
    [Migration("20230516213536_Easy DB")]
    partial class EasyDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Glosolalia.Common.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.PartOfSpeech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PartsOfSpeech");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Sheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SheetSet");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int?>("TranslationId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TranslationId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastInput")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PartOfSpeechId")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<int?>("SheetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartOfSpeechId");

                    b.HasIndex("SheetId");

                    b.ToTable("Translation");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int?>("TranslationId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TranslationId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("LanguageTranslation", b =>
                {
                    b.Property<int>("LanguageSetId")
                        .HasColumnType("int");

                    b.Property<int>("TranslationSetId")
                        .HasColumnType("int");

                    b.HasKey("LanguageSetId", "TranslationSetId");

                    b.HasIndex("TranslationSetId");

                    b.ToTable("LanguageTranslation");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Tag", b =>
                {
                    b.HasOne("Glosolalia.Common.Entities.Translation", null)
                        .WithMany("Tags")
                        .HasForeignKey("TranslationId");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Translation", b =>
                {
                    b.HasOne("Glosolalia.Common.Entities.PartOfSpeech", "PartOfSpeech")
                        .WithMany()
                        .HasForeignKey("PartOfSpeechId");

                    b.HasOne("Glosolalia.Common.Entities.Sheet", null)
                        .WithMany("TranslationSet")
                        .HasForeignKey("SheetId");

                    b.Navigation("PartOfSpeech");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Word", b =>
                {
                    b.HasOne("Glosolalia.Common.Entities.Language", "Language")
                        .WithMany("WordSet")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glosolalia.Common.Entities.Translation", null)
                        .WithMany("TranslatableSet")
                        .HasForeignKey("TranslationId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("LanguageTranslation", b =>
                {
                    b.HasOne("Glosolalia.Common.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glosolalia.Common.Entities.Translation", null)
                        .WithMany()
                        .HasForeignKey("TranslationSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Language", b =>
                {
                    b.Navigation("WordSet");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Sheet", b =>
                {
                    b.Navigation("TranslationSet");
                });

            modelBuilder.Entity("Glosolalia.Common.Entities.Translation", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("TranslatableSet");
                });
#pragma warning restore 612, 618
        }
    }
}
